### ISSUE TITLE
BUG With nested object

### ISSUE THREAD

**Issue by orlandodemauro** [Ivshti/linvodb3#91]
hi guys,

first of all thanks for you great work. I´m having issues with the schemas with nested objects i.e.:

```
cosnt Project = new LinvoDB('Projet', {
  name: { type: String },
  creationDateTime: { type: Number },
  description: { type: String, default: null },
  state: { type: String, enumerable: ['new', 'errors', 'warnings', 'checked'] },
  user: { name: String, email: String, password: Number }
},{});

Promise.promisifyAll(Project);

Project.saveAsync({
                  "name": "test",
                  "description": "test2"
});
```
is saving the model corectly: `{ name: "test", creationDate: "29/06/2018", description: "test2", state: "", user: { name:"", email:"", password: ""}}`

but saving a new object is adding a nested schema property in user: `{ name: "test2", creationDate: "29/06/2018", description: "test3", state: "", user: { schema: { name:"", email:"", password: "" }, type: {}}`

and adding a new object it is nesting a new schema property  `{ name: "test3", creationDate: "29/06/2018", description: "test4", state: "", user: { schema: { schema:{ schema: { name:"", email:"", password: "" }, type:{} }, type: {} }, type: {} } }`

any suggestions on how to fix it?

the bug is reproducible with the version 3.25.1

**Comment by orlandodemauro** [comment]
@Ivshti any suggestion?

**Comment by Ivshti** [comment]
I haven't looked at this for a long time, trying to wrap my head around it atm

It does seem like a nasty bug

**Comment by Ivshti** [comment]
Just looked at your fix now - it makes sense

**Comment by Ivshti** [comment]
@orlandodemauro if you're now sure the bug is fixed, I suggest that, if you have time, you should write a test case (shouldn't take too long)

Also should I publish a new version now?

**Comment by orlandodemauro** [comment]
@Ivshti yes it is fixed, I´m trying to add a unit test but I´m getting this error  

> Uncaught InitializationError: First argument must be an abstract-leveldown compliant store

looks that the file workspace/test3.db is missing. how can i generate it?

meanwhile could you please publish a new version of the package?

**Comment by orlandodemauro** [comment]
@Ivshti could you please push a new version of the module? thank you. and please let me know how to let the 4 test failing pass

**Comment by orlandodemauro** [comment]
@Ivshti pleaseeeeeeeeeeee push a new version :)

**Comment by orlandodemauro** [comment]
@Ivshti is there anything blocking the push of the new version?

**Comment by nicutimofte** [comment]
I still have this issue with the latest version '3.25.2'. How did you manage to solve it?
